CREATE DATABASE AccountApp;

USE AccountApp;

CREATE TABLE Accounts (
    Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
    Username NVARCHAR(100) NOT NULL,
    Password NVARCHAR(200) NOT NULL,
    Salt NVARCHAR(200) NOT NULL,
    Role NVARCHAR(10),
    Email NVARCHAR(100) NOT NULL,
    RegistrationEmail NVARCHAR(100),
    CreatedAt DATETIME NOT NULL,
    UpdatedAt DATETIME,
    LastAttemptIp NVARCHAR(46),
    LastIp NVARCHAR(46),
    Os NVARCHAR(30)
);

SELECT * FROM Accounts;